---
title: "NYC Restaurants Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)

data("rest_inspec")
```

```{r restrict dataset, include = FALSE}
nyc_inspection = 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  filter(inspection_date >= '2017-01-01',
         boro != "Missing") %>% 
  rename(borough = boro) %>% 
  mutate(borough = str_to_title(borough))
```

Column {data-width = 650}
-----------------------------------------------------------------------

### In each borough, how many restaurants were inspected in 2017?

```{r Q1}
rest_insp = tibble(
  nyc_inspection %>%
  group_by(borough) %>% 
  summarize(n_restaurant = n())) 
 
rest_insp %>% 
  mutate(borough = fct_reorder(borough, n_restaurant)) %>% 
  plot_ly(
    x = ~borough, y = ~n_restaurant, color = ~borough,
    type = "bar") %>% 
  layout(title = 'Number of restaurants inspected in 2017', 
         plot_bgcolor = "#e5ecf6", 
         xaxis = list(title = 'Borough'), 
         yaxis = list(title = 'Number of restaurant'), 
         legend = list(title = list(text = 'Borough')))
```


Column {data-width = 350}
-----------------------------------------------------------------------

### Among the inspected restaurant in each borough, what proportion of them received grade A for their inspections?

```{r Q2}
grade_A = tibble(
  nyc_inspection %>%
  filter(grade == "A") %>% 
  group_by(borough) %>% 
  summarize(n_A_rest = n()))
  
nyc_grade_A = 
  full_join(rest_insp, grade_A, by = "borough") %>% 
  mutate(
    percent_A = (n_A_rest / n_restaurant) * 100,
    percent_A = round(percent_A, digits = 2))

nyc_grade_A %>% 
  plot_ly(
    labels = ~borough,
    values = ~percent_A,
    type = 'pie',
    text = 'percent_A',
    textposition = "inside",
    textinfo = "value") %>%
  layout(
    title = "Proportion of grade A restaurants in each borough (%)",
    textinfo = 'values',
    xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
    yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
    legend = list(title = list(text = 'Borough')))
```


### What are the top 10 most common violation codes among the inspected restaurants in 2017?

```{r Q3}
violation = 
  nyc_inspection %>%
  count(violation_code) %>% 
  arrange(desc(n)) %>% 
  slice(1:10)

violation = 
  violation %>% 
  mutate(
    description = case_when(
      violation_code == "10F" ~ 'Non-food contact surfaces improperly constructed/maintained',
      violation_code == "08A" ~ 'Pest-related conditions',
      violation_code == "04L" ~ 'Evidence of mice',
      violation_code == "06C" ~ 'Food not protected from contamination',
      violation_code == "06D" ~ 'Food contact surfaces not clean and sanitized',
      violation_code == "10B" ~ 'Potable water not protected from backflow / Improper disposal of sewage or liquid waste',
      violation_code == "02G" ~ 'Cold potentially hazardous food not held at 41F or below',
      violation_code == "02B" ~ 'Hot potentially hazardous food not held at 140F or above',
      violation_code == "04N" ~ 'Filth flies',
      TRUE ~ 'Food not protected from cross-contamination/toxic material')) %>% 
  rename(n_times_violated = n)

violation %>% 
  select(violation_code, description, n_times_violated) %>% 
  knitr::kable()
```

